### ISSUE TITLE
Feature request: export history to local history file

### ISSUE THREAD

**Issue by zxh326** [ellie/atuin#1073] opened 2023-06-25 12:12 UTC
After I set up `atuin sync` on the new device, I found that fish Auto Suggestions are not working. 

Guess it's because there is no command history in the fish's history file.

So, can we add an command to export `atuin history` to the local history file?

**Comment by zxh326** [comment] 2023-06-28 06:45
Wrote a simple script to export history into fish local file.

```go
package main

import (
	"database/sql"
	"fmt"
	"os"

	_ "github.com/mattn/go-sqlite3"
)

var (
	home string
)

func init() {
	home, _ = os.UserHomeDir()
}

func writeFishHistoryFile(t int, cmd string) {
	file, err := os.OpenFile(home+"/.local/share/fish/fish_history", os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0644)
	if err != nil {
		panic(err)
	}
	defer file.Close()
	content := fmt.Sprintf("- cmd: %s\n  when: %d\n", cmd, t/1000000000)

	_, err = file.WriteString(content)
	if err != nil {
		panic(err)
	}
}

func main() {
	db, err := sql.Open("sqlite3", home+"/.local/share/atuin/history.db")
	if err != nil {
		fmt.Println(err)
		return
	}
	defer db.Close()

	rows, err := db.Query("SELECT * FROM history ORDER BY timestamp ASC")
	if err != nil {
		fmt.Println(err)
		return
	}
	defer rows.Close()

	for rows.Next() {
		var id, command, cwd, session, hostname string
		var timestamp, duration, exit int
		var deleted_at interface{}

		err = rows.Scan(&id, &timestamp, &duration, &exit, &command, &cwd, &session, &hostname, &deleted_at)
		if err != nil {
			fmt.Println(err)
			continue
		}

		writeFishHistoryFile(timestamp, command)
	}

	err = rows.Err()
	if err != nil {
		fmt.Println(err)
		return
	}
}

```

**Comment by ellie** [comment] 2023-07-03 07:47
Thank you for the script! Otherwise, this is a a dupe of #816

**Closed by ellie** 2023-07-03 07:47 UTC

**Comment by tjheeta** [comment] 2024-01-27 05:09
```$ atuin history list | cut -f2- | rev | cut -f2-|rev``` gives a .bash_history compatible export by removing the first and last columns.

**Comment by potoo0** [comment] 2024-04-10 11:21
for zsh_history

```python
import subprocess
from datetime import datetime

dst = 'zsh_history.out'
cmd = 'atuin history list --format {time}:0;{command}'
p = subprocess.Popen(cmd.split(), stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
with open(dst, 'w', encoding='utf8') as f_dst:
    line_continue = False
    while True:
        line = p.stdout.readline()
        if line == b'':
            break

        line = line.decode(encoding='utf-8')
        if line_continue:
            f_dst.write(line)
        else:
            try:
                dt = datetime.strptime(line[0:19], '%Y-%m-%d %H:%M:%S')
                f_dst.write(f': {int(dt.timestamp())}')
                f_dst.write(line[19:])
            except ValueError as e:
                print(f'error={e}, line={line}')
        line_continue = line.rstrip().endswith('\\')

```

**Comment by mdreher-align** [comment] 2024-09-05 10:42
Thanks @potoo0, I adjusted the command for zsh history format to handle multi-line output with the --print0 flag:

```python
import subprocess
from datetime import datetime

dst = "zsh_history.out"
cmd = "atuin history list --print0 --format {time}:0;{command}".split()
p = subprocess.run(cmd, check=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)

with open(dst, "w", encoding="utf8") as f_dst:
    for line in p.stdout.decode("utf-8").split("\0"):
        if not line:
            continue
        dt = datetime.strptime(line[:19], "%Y-%m-%d %H:%M:%S")
        f_dst.write(f": {int(dt.timestamp())}")
        f_dst.write(line[19:].replace("\n", "\\\n"))
        f_dst.write("\n")
```

**Comment by potoo0** [comment] 2024-09-05 10:47
> Thanks @potoo0, I adjusted the command for zsh history format to handle multi-line output with the --print0 flag:
> 
> ```python
> import subprocess
> from datetime import datetime
> 
> dst = "zsh_history.out"
> cmd = "atuin history list --print0 --format {time}:0;{command}".split()
> p = subprocess.run(cmd, check=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
> 
> with open(dst, "w", encoding="utf8") as f_dst:
>     for line in p.stdout.decode("utf-8").split("\0"):
>         if not line:
>             continue
>         dt = datetime.strptime(line[:19], "%Y-%m-%d %H:%M:%S")
>         f_dst.write(f": {int(dt.timestamp())}")
>         f_dst.write(line[19:].replace("\n", "\\\n"))
>         f_dst.write("\n")
> ```

excellent
