### ISSUE TITLE
Add a key binding or configuration to run selected command immediately

### ISSUE THREAD

**Issue by cheuk-cheng** [ellie/atuin#906] opened 2023-04-22 17:02 UTC
I am new to atuin but I had used resh and mcfly before.  Is there a way in autin to run a command in history immediately without pressing <enter> key?  Thanks.

**Comment by VuiMuich** [comment] 2023-04-22 20:05
This is a duplicate of #78 and I just started looking into this matter with draft PR #907.

**Comment by ellie** [comment] 2023-04-28 23:16
Closing as a dupe, thanks @VuiMuich

**Closed by ellie** 2023-04-28 23:16 UTC

**Comment by VuiMuich** [comment] 2023-04-29 11:55
> Closing as a dupe, thanks @VuiMuich 

You are very welcome!
