### ISSUE TITLE
atuin disables shell local echo

### ISSUE THREAD

**Issue by HHPLow** [ellie/atuin#617] opened 2022-11-17 07:18 UTC
OS: Ubuntu 20.04 LTS
Atuin version: 12.0.0
Shell: bash  5.0.17

**Issue**: atuin disabled shell local echo and will not enable till run `stty echo`

**Behavior**:
```shell
$ ssh not-exist-remote                          # first time run
^C
$ ssh not-exist-remote                          # use atuin run again
^C
$ $ $ $ $ $                                     # local echo disable
$                                               # after run "stty echo"
$
```

**How to reproduce**:
1. run one cmd that spent a long time or never exit(like `ssh not-exist-remote`)
2. `ctrl + C` kill this
3. `ctrl + R` use atuin run again
4. `ctrl + C` kill this
5. press enter key, then you get it

**Comment by conradludgate** [comment] 2022-11-17 08:09
Might be a duplicate of #492

**Comment by HHPLow** [comment] 2022-11-17 08:29
oh yes, the same issue but in a different way. thanks~

I searched "local echo" but not found the issue, so raise this issue.

**Comment by ellie** [comment] 2022-11-27 17:48
Closing as dupe

**Closed by ellie** 2022-11-27 17:48 UTC
