### ISSUE TITLE
atuin on ARM64

### ISSUE THREAD

**Issue by willifehler** [ellie/atuin#1121] opened 2023-07-27 06:53 UTC
Hello,

I would like to use atuin on ARM64 (Debian). I can see in the install script that there is a amd64.deb package.

ARTIFACT_URL="https://github.com/ellie/atuin/releases/download/$LATEST_VERSION/atuin_${LATEST_VERSION//v/}_amd64.deb"

Would it be possible to build atuin for ARM64?

Thank you so much for this wonderful peace of software.

Cheers - Willi

**Comment by ellie** [comment] 2023-07-27 06:56
Hey! We're looking at this at the moment, but would like to ensure it's done properly. Dupe of #1032

**Comment by willifehler** [comment] 2023-07-27 06:58
Thank you Ellie.

**Closed** 2023-07-27 07:00 UTC
