### ISSUE TITLE
Raspberry Pi version of the self hosting server Docker image

### ISSUE THREAD

**Issue by alastairhm** [ellie/atuin#1116] opened 2023-07-25 14:30 UTC
Can you build a Raspberry Pi compatible version of the self hosting Docker image?
This is the error you get at the moment.

```
pi@raspberrypi:~ $ docker pull ghcr.io/ellie/atuin:main
main: Pulling from ellie/atuin
no matching manifest for linux/arm64/v8 in the manifest list entries
pi@raspberrypi:~ $

```

**Comment by ellie** [comment] 2023-07-25 14:48
Dupe of #1032

**Closed by ellie** 2023-07-25 14:48 UTC
