### ISSUE TITLE
Add a feature to disable history

### ISSUE THREAD

**Issue by kelvinhammond** [ellie/atuin#954] opened 2023-05-07 23:16 UTC
Occasionally I need to disable history for various reasons (removing a lot of files or passwords passed on the command line) during my workflow. I currently disable history by setting the `HISTFILE` environment variable but with atuin I can't do this because it uses pre-command hooks.

Is there currently a way to disable history for the current shell session and if not can you add a way to do so?

**Comment by YummyOreo** [comment] 2023-05-08 13:05
duplicate of #517. Currently you can put a space before the command and it will not be recorded. Or if your using fish, you can set private mode thingy

**Closed** 2023-05-08 13:13 UTC
