### ISSUE TITLE
Add keybinding and/or command to remove history entries

### ISSUE THREAD

**Issue by ozeebee** [ellie/atuin#259] opened 2022-01-04 17:53 UTC
Hi there !

Any chance to have a key binding in the UI or CLI command to remove history entries ?
I often enter incorrect commands at the prompt (typo, etc.) and they clutter my history with the risk of selecting these erroneous commands to execute them again.
So I think it would be great to be able to remove these entries (especially in the UI).
Many thanks !

**Comment by ellie** [comment] 2022-10-08 04:39
Dupe of #70!

tl;dr, sync makes deleting things _difficult_. We can delete from the client, but after a sync it'll just come right back. So we need a nice and consistent way of deleting across all machines

**Closed** 2022-10-08 04:39 UTC
Labels: duplicate
