### ISSUE TITLE
Using ^C interrupt to kill a command which atuin completed causes the terminal to stop echoing input characters

### ISSUE THREAD

**Issue by itszn** [ellie/atuin#1012] opened 2023-05-28 17:55 UTC
For some reason when running commands I completed with atuin, if I kill the command with ^C it breaks my terminal's tty echoing mode. This makes all my input invisible until I run `reset`.
Unfortunately this is really inconvenient and has lead to several potentially dangerous mistakes when my terminal characters suddenly get hidden when I'm doing something important or precise during devops, with the only fix seeming to be clearing my whole terminal buffer with `reset`. I will have to disable atuin until I find a workaround...

Steps to reproduce
- run `sleep 1000` so the command is in your history
- ctrl+r and type `sleep`, select the entry, hit enter
- hit enter again to run the command, type something to confirm that input chars are being echoed by the tty
- hit ^C to kill sleep
- try to type again, input chars are no long being echoed by the tty

Video of it in action:
https://github.com/ellie/atuin/assets/1857794/f14f9e0d-8787-46e7-8fde-3ac52bd4931c

^ In both cases I type `echo world` after hitting ^C. WIth atuin, the tty stops echoing my input once I hit ^C. Also it seems to mess up the rendering of the output of the echo command?

Environment:
Windows Terminal Stable ssh'ed to a Ubuntu 22.04 bash shell.
Starting atuin in my `.bashrc` with `eval "$(atuin init bash --disable-up-arrow)"`

I have the following config, **but it reproduces on the default config for me**:
```
search_mode = "fulltext"
filter_mode = "session"
style = "compact"
inline_height = 10
show_preview = true
exit_mode = "return-query"
```

Some ENV variables (if they are helpful):
```
SHELL=/bin/bash
TERM=xterm-256color
PS1=\[\033[01;31m\]\u\[\]\[\033[01;30m\]@\[\]\[\033[01;32m\]\h\[\]\[\033[00m\]:\[\]\[\033[01;34m\]\W\[\]\[\033[38;5;15m\]\$\[\]
SSH_TTY=/dev/pts/23
```

**Comment by PMeira** [comment] 2023-05-28 22:09
This is a duplicate of https://github.com/ellie/atuin/issues/996, no?

**Closed** 2023-05-28 22:12 UTC
