### ISSUE TITLE
missing field `history` when syncing new machine

### ISSUE THREAD

**Issue by james-smith-za** [ellie/atuin#976] opened 2023-05-12 07:46 UTC
Lovely piece of software! Been using for a little while, tried syncing a new machine today.

I get the following though (on the new computer):
```
jsmith@qgpu02 ~ $ atuin sync
Error: error decoding response body: missing field `history` at line 1 column 50

Caused by:
    missing field `history` at line 1 column 50

Location:
    /home/runner/work/atuin/atuin/atuin-client/src/api_client.rs:179:23
```

Login seemed fine, but syncing didn't happen. Where to start looking for further debug information?

**Comment by ellie** [comment] 2023-05-13 18:41
Hey! Are you using bash?

**Comment by stratosgear** [comment] 2023-05-13 21:30
Same just happened to me too, on a new machine.  I run in zsh 

```
atuin --version
atuin 14.0.1

zsh --version
zsh 5.9 (x86_64-pc-linux-gnu)
```

**Comment by ellie** [comment] 2023-05-13 21:31
Hey! Have either of you ever imported any Bash history?

**Comment by stratosgear** [comment] 2023-05-14 10:35
I have!

I did a bash import sometime ago.  But I recently switched to zsh!

**Comment by bob454522** [comment] 2023-05-15 16:33
I might be able to help w this -  i was debugging this exact same issue w ellie via discord a few days ago-  it was a bug that has since been fixed in the latest version of main (bug has NOT been built into the current .deb packages yet though).   Its a bug related to bash and its history file not having timestamps and/OR the usage of nanoseconds/milliseconds in PostgreSQL db-  the the link at bottom

so you have the build the latest atuin from main (was patched 3-4 days ago),  in MY case:
(uninstall atunin):
`cargo install --git https://github.com/ellie/atuin.git --branch main`

or to overwrite the atuin binary in-place:
`cargo install --git https://github.com/ellie/atuin.git --branch main --force`

now the part im not sure on: is if u you need to fully start from fresh after doing this (ie if you are selfhosting the atuin server,  like im doing,  drop the DB and re-import each of your atuin clients.)   <  so i cant say if you can just update the atuin client and then try:   `atuin import auto`  then    `atuin sync`    OR if you need to fully start over / re-import on all of your atuin clients.

that said- the solution to ur issue starts with using the very latest version of atuin,  which addresses this bug:
https://github.com/ellie/atuin/pull/970

**Comment by stratosgear** [comment] 2023-05-16 16:46
Your recovery instructions (I believe) does not cover the case where I have stored history on the public atuin sync server, from machines that I do no longer have access.  So I cannot force another sync from those.

I am not sure if the following makes sense, or if it is even doable but, assuming that a proper fix will be available some time soon, through another upcoming release, so that we do not have to manually build, would be to:

1. Keep using atuin in the new local machine, until the new release is out.  This will create a local db, that unfortunately will NOT be synced with my previous online synced history.
2. When the new release is available, somehow export(?) my local history
3. Destroy as you said my local db, so I get the new schema
4. Reimport my export into the new db, and then sync online so I regain all the previous history that I have stored online.

I guess I have to see how I can export/import my db now.  Although I would hope there would be some db migration scripts that should take care of it, no...?

Or even better a documented way on how to do this, maybe... :)

**Comment by ellie** [comment] 2023-05-17 20:40
Unfortunately not, as the issue presently is with the data in remote storage. With the change in #845, we started losing timestamp precision on the server for bash history imports that did not have timestamp info.

Essentially, local history has nanosecond precision but we were throwing away anything higher precision than microseconds on the server (turns out postgres timestamp fields don't go that far). This was no big deal until the aforementioned change, which relied on nanosecond precision.

Future imports are fixed, and I have some thoughts on how we can fix syncing the currently-existing data without having to clear it, though it is a wider change.

There are no issues with your local DB though, and we will not need to touch that data

**Comment by james-smith-za** [comment] 2023-05-18 09:18
I'm happy to wipe out histories and start from scratch - I don't have anything precious in there at the moment. Syncing is also a nice-to-have but not essential.

Unfortunately I'm not going to have much time to experiment though, work is pretty busy lately...

**Comment by stratosgear** [comment] 2023-05-18 10:13
If we are offering opinions here, in this mini "survey" :) , I would prefer if I would be able to keep all the online history, since I often have to consult how I did something in the past.  That is the main reason why I would be using atuin, after all.

Maybe there is a way to export and reimport the history entries?

I see I can do a `atuin history list` to get all entries, but not a way to feed them back into atuin...?

**Comment by ellie** [comment] 2023-05-21 15:13
I'm fairly sure that #994 should also resolve this, though I've found consistently reproducing the issue tricky

Default page size on the client of >1000 should mean that loss of nano precision isn't a big deal for new clients

**Comment by ellie** [comment] 2023-05-21 15:14
> Apart from a manual build, that I would like to avoid doing, is the next release going to "automatically" take care of it? 

I am very much hoping that the next release should automatically resolve this, worst case some manual steps

**Comment by yannickulrich** [comment] 2023-05-21 17:10
> I'm fairly sure that #994 should also resolve this, though I've found consistently reproducing the issue tricky

I can confirm that the issue is gone with the current main branch on both machines where I experienced it with 🥳

**Closed** 2023-05-31 12:44 UTC
