### ISSUE TITLE
Feature request: execute selected command immediately

### ISSUE THREAD

**Issue by patik** [ellie/atuin#957] opened 2023-05-08 07:48 UTC
When I find an item in my history, I'd like to be able to run the command with one keystroke.

Ideally I would be able to configure Atuin like this:

* When a history item is selected, pressing enter would close Atuin and execute the command immediately
* When a history item is selected, pressing right arrow would place that item on the prompt (i.e. this is what the enter key does currently)

**Comment by conradludgate** [comment] 2023-05-08 09:16
Dupe of #78

**Closed by conradludgate** 2023-05-08 09:16 UTC
