### ISSUE TITLE
Server migration to latest version

### ISSUE THREAD

**Issue by rjshrjndrn** [ellie/atuin#1037] opened 2023-06-08 10:56 UTC
Hi,
Thank you for this amazing tool. I'm running a self-hosted version of atuin, and today I tried to migrate to the latest version. But facing the following issue.
```
Caused by:
   0: while executing migrations: error returned from database: syntax error at or near "trigger"
   1: while executing migrations: error returned from database: syntax error at or near "trigger"
   2: error returned from database: syntax error at or near "trigger"
   3: syntax error at or near "trigger"
```

**Comment by conradludgate** [comment] 2023-06-08 11:27
Dupe of #1031

**Closed by conradludgate** 2023-06-08 11:27 UTC
